#!/usr/bin/env bash
# Regenerate the Rust model files used by the judge (server/src/generated/).
#
# The judge compiles XGBoost into Rust via m2cgen so it can score submissions
# in-process with zero runtime deps. Run this after retraining a model.
#
# Usage:  ./regenerate_models.sh [python] [artifacts-dir]
# Requires: a Python venv at ./.venv with `m2cgen` and `joblib` installed.
#
# NOTE: model-training's venv script is `./.venv/bin/python` (hidden dir).
# If you use a different venv path, edit PY below.
# The artifacts dir defaults to ./artifacts; pass e.g. ./artifacts_codenet_v2 to
# ship a different trained model set without moving files around.
set -euo pipefail
cd "$(dirname "$0")"

PY="${1:-./.venv/bin/python}"
export OUT="${OUT:-../server/src/generated}"
export ARTIFACTS="${2:-./artifacts}"
mkdir -p "$OUT"

# Base score: XGBoost 3.x stores base_score=None but the true offset is 0.5.
# m2cgen crashes on None, so we set it explicitly (does NOT change predictions).
"$PY" - <<'PY'
import m2cgen as m2c, joblib, os
outdir = os.environ["OUT"]
artdir = os.environ["ARTIFACTS"]
# artifact basename (joblib) -> model key, feature count, output rust filename
# Feature counts MUST match `get_feature_cols()` in train_advanced_xgboost.py and
# `specialized_features`/`unified_features` in server/src/predict.rs. A mismatch is
# not caught at runtime (both sides index positionally), so the guard below verifies
# each trained model against this table before writing any Rust.
jobs = [
    ("model_specialized_python", "python", 36, "specialized_python.rs"),
    ("model_specialized_cpp",    "cpp",   36, "specialized_cpp.rs"),
    ("model_specialized_java",   "java",  36, "specialized_java.rs"),
    ("model_unified_multi-language", "unified", 40, "unified_multi_language.rs"),
]
for job, key, nfeat, fname in jobs:
    m = joblib.load(os.path.join(artdir, f"{job}.joblib"))
    m.base_score = 0.5  # fix XGBoost 3.x None bug for m2cgen
    # guard: verify the trained model's OWN feature count, not just our expectation
    n_actual = m.get_booster().num_features()
    if n_actual != nfeat:
        raise SystemExit(
            f"feature count mismatch for {job}: model has {n_actual}, expected {nfeat}"
        )
    src = m2c.export_to_rust(m, function_name="score")
    path = os.path.join(outdir, fname)
    with open(path, "w") as f:
        f.write(f"// Auto-generated by model-training/regenerate_models.sh — DO NOT EDIT.\n")
        f.write(f"// model={job}  features={nfeat}  xgboost->m2cgen\n")
        f.write("// Generator: `m2cgen.export_to_rust` with base_score=0.5\n")
        # make score public so the sibling predict module can reach it
        src = src.replace("fn score(", "pub fn score(", 1)
        f.write(src)
    print(f"wrote {fname} ({nfeat} features)")
PY
echo "Done. Next: rebuild the judge  ->  cd server && cargo build"
